version: "3.8"

services:
  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
